/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelos.Tarea;
import modelos.Usuario;

/**
 *
 * @author Silvia Tovar
 */
public class UsuarioFrame extends javax.swing.JFrame {

    private String rutaUsuario = new String("datos/usuario.dat");
    private String rutaTarea = new String("datos/tarea.dat");
    private final InputStream inputUsuario = getClass().getResourceAsStream(rutaUsuario);
    private final InputStream inputTarea = getClass().getResourceAsStream(rutaTarea);
    private static Usuario usu;
    private static List<Usuario> usuarios;
    private static Tarea tarea;
    private static List<Tarea> tareas;
    private static int contadorIntento;
    private final int longMinNombreUsuario = 3;
    private final int longMinContrasenaUsuario = 6;

    /**
     * Creates new form UsuarioFrame
     */
    public UsuarioFrame() {
        initComponents();
        usu = new Usuario();
        usuarios = new ArrayList();
        tareas = new ArrayList();
        this.contadorIntento = 1;
        contenedor.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedor = new javax.swing.JTabbedPane();
        inicio = new javax.swing.JPanel();
        logoRasilu = new javax.swing.JLabel();
        bgFondo = new javax.swing.JLabel();
        logoName = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        textContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        registro = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        botonRegistro = new javax.swing.JButton();
        botonAcceder1 = new javax.swing.JButton();
        menuRegistro = new javax.swing.JPanel();
        logoRasilu1 = new javax.swing.JLabel();
        bgFondo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        iniciarSesion1 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        contraseña1 = new javax.swing.JLabel();
        textUsuario1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        textContraseña1 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        botonInicio = new javax.swing.JButton();
        textContraseña2 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        confirmarContraseña = new javax.swing.JLabel();
        botonRegistro1 = new javax.swing.JButton();
        menuTareas = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        bgFondo2 = new javax.swing.JLabel();
        oclock = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        fechaFin = new javax.swing.JLabel();
        textFechaFin = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        botonGuardar = new javax.swing.JButton();
        textTitulo = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        addBoton = new javax.swing.JButton();
        modificarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        lista1 = new javax.swing.JScrollPane();
        tituloLista = new javax.swing.JList<>();
        lista2 = new javax.swing.JScrollPane();
        duracionLista = new javax.swing.JList<>();
        lista3 = new javax.swing.JScrollPane();
        estadoLista = new javax.swing.JList<>();
        pendiente = new javax.swing.JRadioButton();
        enProceso = new javax.swing.JRadioButton();
        finalizado = new javax.swing.JRadioButton();
        fechaInicio1 = new javax.swing.JLabel();
        textFechaInicio = new javax.swing.JTextField();
        botonSalirTarea = new javax.swing.JButton();
        botonVolverInicioTarea = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        inicio.setBackground(new java.awt.Color(255, 255, 255));
        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoRasilu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo rasilu.png"))); // NOI18N
        inicio.add(logoRasilu, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 240, 130));

        bgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoflores.png"))); // NOI18N
        bgFondo.setText("jLabel2");
        inicio.add(bgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -10, 280, 600));

        logoName.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        logoName.setText("O´clock");
        inicio.add(logoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 50));

        logo.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopequeño.png"))); // NOI18N
        inicio.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 280, 90));

        iniciarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        iniciarSesion.setText("INICIAR SESION");
        inicio.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, 50));

        usuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        usuario.setText("USUARIO");
        inicio.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contraseña.setText("CONTRASEÑA");
        inicio.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 20));

        textUsuario.setForeground(new java.awt.Color(204, 204, 204));
        textUsuario.setText("Escriba aquí su nombre..");
        textUsuario.setAutoscrolls(false);
        textUsuario.setBorder(null);
        textUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textUsuarioMousePressed(evt);
            }
        });
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        inicio.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 330, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        inicio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 310, 10));

        textContraseña.setForeground(new java.awt.Color(204, 204, 204));
        textContraseña.setText("******");
        textContraseña.setBorder(null);
        textContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraseñaMousePressed(evt);
            }
        });
        textContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseñaActionPerformed(evt);
            }
        });
        inicio.add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        inicio.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 310, 20));

        registro.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        registro.setText("¿Aún no estás registrado?");
        inicio.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, 30));

        botonSalir.setBackground(new java.awt.Color(221, 152, 123));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("SALIR");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSalirMousePressed(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        inicio.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 80, 30));

        botonRegistro.setBackground(new java.awt.Color(221, 152, 123));
        botonRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistro.setText("REGISTRATE AQUI");
        botonRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRegistroMousePressed(evt);
            }
        });
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        inicio.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 140, 30));

        botonAcceder1.setBackground(new java.awt.Color(221, 152, 123));
        botonAcceder1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAcceder1.setForeground(new java.awt.Color(255, 255, 255));
        botonAcceder1.setText("ACCEDER");
        botonAcceder1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAcceder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAcceder1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAcceder1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAcceder1MousePressed(evt);
            }
        });
        botonAcceder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcceder1ActionPerformed(evt);
            }
        });
        inicio.add(botonAcceder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 90, 30));

        contenedor.addTab("Usuario", inicio);

        menuRegistro.setBackground(new java.awt.Color(255, 255, 255));
        menuRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoRasilu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo rasilu.png"))); // NOI18N
        menuRegistro.add(logoRasilu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 240, 130));

        bgFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoflores.png"))); // NOI18N
        bgFondo1.setText("jLabel2");
        menuRegistro.add(bgFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -10, 280, 600));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("O´clock");
        menuRegistro.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 50));

        logo1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopequeño.png"))); // NOI18N
        menuRegistro.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 280, 90));

        iniciarSesion1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        iniciarSesion1.setText("NUEVA CUENTA");
        menuRegistro.add(iniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 180, 50));

        usuario1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        usuario1.setText("NOMBRE DE USUARIO");
        menuRegistro.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        contraseña1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contraseña1.setText("CONTRASEÑA");
        menuRegistro.add(contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, 20));

        textUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        textUsuario1.setText("Escriba aquí su nombre..");
        textUsuario1.setAutoscrolls(false);
        textUsuario1.setBorder(null);
        textUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textUsuario1MousePressed(evt);
            }
        });
        textUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuario1ActionPerformed(evt);
            }
        });
        menuRegistro.add(textUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 330, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        menuRegistro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 310, 10));

        textContraseña1.setForeground(new java.awt.Color(204, 204, 204));
        textContraseña1.setText("******");
        textContraseña1.setBorder(null);
        textContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraseña1MousePressed(evt);
            }
        });
        textContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseña1ActionPerformed(evt);
            }
        });
        menuRegistro.add(textContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 170, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        menuRegistro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 310, 20));

        botonInicio.setBackground(new java.awt.Color(221, 152, 123));
        botonInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonInicio.setForeground(new java.awt.Color(255, 255, 255));
        botonInicio.setText("VOLVER A INICIO");
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonInicioMousePressed(evt);
            }
        });
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        menuRegistro.add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 140, 30));

        textContraseña2.setForeground(new java.awt.Color(204, 204, 204));
        textContraseña2.setText("******");
        textContraseña2.setBorder(null);
        textContraseña2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraseña2MousePressed(evt);
            }
        });
        textContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseña2ActionPerformed(evt);
            }
        });
        menuRegistro.add(textContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        menuRegistro.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 310, 10));

        confirmarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmarContraseña.setText("CONFIRMAR CONTRASEÑA");
        menuRegistro.add(confirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 20));

        botonRegistro1.setBackground(new java.awt.Color(221, 152, 123));
        botonRegistro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistro1.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistro1.setText("REGISTRARSE");
        botonRegistro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistro1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistro1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRegistro1MousePressed(evt);
            }
        });
        botonRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistro1ActionPerformed(evt);
            }
        });
        menuRegistro.add(botonRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 110, 30));

        contenedor.addTab("Registro", menuRegistro);

        menuTareas.setBackground(new java.awt.Color(255, 255, 255));
        menuTareas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo rasilu.png"))); // NOI18N
        Logo.setToolTipText("");
        Logo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuTareas.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 280, 130));

        bgFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoflores.png"))); // NOI18N
        bgFondo2.setText("jLabel2");
        menuTareas.add(bgFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 280, 580));

        oclock.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        oclock.setText("O´clock");
        menuTareas.add(oclock, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 50));

        logo2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopequeño.png"))); // NOI18N
        menuTareas.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 280, 90));

        titulo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        titulo.setText("TITULO");
        menuTareas.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        fechaFin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaFin.setText("Fecha fin ");
        menuTareas.add(fechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, 20));

        textFechaFin.setForeground(new java.awt.Color(204, 204, 204));
        textFechaFin.setText("Escriba aquí la duración de su tarea...");
        textFechaFin.setAutoscrolls(false);
        textFechaFin.setBorder(null);
        textFechaFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFechaFinMousePressed(evt);
            }
        });
        textFechaFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaFinActionPerformed(evt);
            }
        });
        menuTareas.add(textFechaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 120, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        menuTareas.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 310, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        menuTareas.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 310, 20));

        botonGuardar.setBackground(new java.awt.Color(221, 152, 123));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonGuardarMousePressed(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        menuTareas.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        textTitulo.setForeground(new java.awt.Color(204, 204, 204));
        textTitulo.setText("Escriba aquí el titulo de su tarea...");
        textTitulo.setAutoscrolls(false);
        textTitulo.setBorder(null);
        textTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textTituloMousePressed(evt);
            }
        });
        textTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloActionPerformed(evt);
            }
        });
        menuTareas.add(textTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 330, 20));

        estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estado.setText("ESTADO");
        menuTareas.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 20));

        addBoton.setBackground(new java.awt.Color(242, 242, 242));
        addBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        addBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        addBoton.setText("Añadir ");
        addBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBotonActionPerformed(evt);
            }
        });
        menuTareas.add(addBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, 40));

        modificarBoton.setBackground(new java.awt.Color(242, 242, 242));
        modificarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        modificarBoton.setText("Modificar ");
        modificarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });
        menuTareas.add(modificarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 100, 40));

        eliminarBoton.setBackground(new java.awt.Color(242, 242, 242));
        eliminarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        eliminarBoton.setText("Eliminar");
        eliminarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });
        menuTareas.add(eliminarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 100, -1));

        tituloLista.setBackground(new java.awt.Color(242, 242, 242));
        tituloLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        tituloLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tituloLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista1.setViewportView(tituloLista);

        menuTareas.add(lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 110, 140));

        duracionLista.setBackground(new java.awt.Color(242, 242, 242));
        duracionLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Duración", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        duracionLista.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        duracionLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        duracionLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        duracionLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lista2.setViewportView(duracionLista);

        menuTareas.add(lista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 110, 140));

        estadoLista.setBackground(new java.awt.Color(242, 242, 242));
        estadoLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        estadoLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        estadoLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista3.setViewportView(estadoLista);

        menuTareas.add(lista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 110, 140));

        pendiente.setText("PENDIENTE");
        pendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendienteActionPerformed(evt);
            }
        });
        menuTareas.add(pendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        enProceso.setText("EN PROCESO");
        enProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enProcesoActionPerformed(evt);
            }
        });
        menuTareas.add(enProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        finalizado.setText("FINALIZADO");
        finalizado.setContentAreaFilled(false);
        finalizado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuTareas.add(finalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        fechaInicio1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        fechaInicio1.setText("Fecha Inicio");
        menuTareas.add(fechaInicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 20));

        textFechaInicio.setForeground(new java.awt.Color(204, 204, 204));
        textFechaInicio.setText("Escriba aquí la duración de su tarea...");
        textFechaInicio.setAutoscrolls(false);
        textFechaInicio.setBorder(null);
        textFechaInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textFechaInicioMousePressed(evt);
            }
        });
        textFechaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFechaInicioActionPerformed(evt);
            }
        });
        menuTareas.add(textFechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 130, 20));

        botonSalirTarea.setBackground(new java.awt.Color(221, 152, 123));
        botonSalirTarea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSalirTarea.setText("Salir");
        botonSalirTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirTareaActionPerformed(evt);
            }
        });
        menuTareas.add(botonSalirTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 80, -1));

        botonVolverInicioTarea.setBackground(new java.awt.Color(221, 152, 123));
        botonVolverInicioTarea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonVolverInicioTarea.setText("Volver al inicio");
        botonVolverInicioTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverInicioTareaActionPerformed(evt);
            }
        });
        menuTareas.add(botonVolverInicioTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, -1, -1));

        contenedor.addTab("Tareas", menuTareas);

        getContentPane().add(contenedor, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void textContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseñaActionPerformed

    private void textUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textUsuarioMousePressed
//       Cuando pasamos el cursor se cambia de color el apartado contrario y viceversa

        if (textUsuario.getText().equals("Escriba aquí su nombre..")) {
            textUsuario.setText("");
            textUsuario.setForeground(Color.black);
        }
        if (String.valueOf(textContraseña.getPassword()).isEmpty()) {
            textContraseña.setText("******");
            textContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textUsuarioMousePressed

    private void textContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraseñaMousePressed
//Estas condiciones se ponen para que cuando escribas en un campo no se borren los datos en el otro
        if (String.valueOf(textContraseña.getPassword()).equals("******")) {
            textContraseña.setText("");
            textContraseña.setForeground(Color.black);
        }

        if (textUsuario.getText().isEmpty()) {
            textUsuario.setText("Escriba aquí su nombre..");
            textUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textContraseñaMousePressed

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirMouseExited

    private void botonSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirMousePressed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        int salir = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas salir?", "", JOptionPane.YES_NO_OPTION);
        if (salir == JOptionPane.YES_OPTION) {
            System.exit(0);
        }

    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroMouseEntered

    private void botonRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroMouseExited

    private void botonRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroMousePressed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed

        contenedor.setSelectedIndex(1);
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void textUsuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textUsuario1MousePressed
        //       Cuando pasamos el cursor se cambia de color el apartado contrario y viceversa

        if (textUsuario1.getText().equals("Escriba aquí su nombre..")) {
            textUsuario1.setText("");
            textUsuario1.setForeground(Color.black);
        }

        if (String.valueOf(textContraseña2.getPassword()).isEmpty()) {
            textContraseña2.setText("******");
            textContraseña2.setText("");
            textContraseña2.setForeground(Color.black);
        }

        if (String.valueOf(textContraseña1.getPassword()).isEmpty()) {
            textContraseña2.setText("******");
            textContraseña1.setText("");
            textContraseña1.setForeground(Color.gray);
        }

    }//GEN-LAST:event_textUsuario1MousePressed

    private void textUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuario1ActionPerformed

    private void textContraseña1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraseña1MousePressed

        //Estas condiciones se ponen para que cuando escribas en un campo no se borren los datos en el otro
        if (String.valueOf(textContraseña1.getPassword()).equals("******")) {
            textContraseña1.setText("*******");
            textContraseña1.setText("");
            textContraseña1.setForeground(Color.black);
        }
        if (textUsuario1.getText().isEmpty()) {
            textUsuario1.setText("Escriba aquí su nombre..");
            textUsuario1.setForeground(Color.gray);
        }
        if (String.valueOf(textContraseña2.getPassword()).equals("******")) {
            textContraseña2.setText("*******");

            textContraseña2.setForeground(Color.gray);
        }


    }//GEN-LAST:event_textContraseña1MousePressed

    private void textContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseña1ActionPerformed

    private void botonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseEntered

    }//GEN-LAST:event_botonInicioMouseEntered

    private void botonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseExited

    }//GEN-LAST:event_botonInicioMouseExited

    private void botonInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInicioMousePressed

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        int volverInicio = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que quiere volver al menú principal?",
                "",
                JOptionPane.YES_NO_OPTION);

        if (volverInicio == JOptionPane.YES_OPTION) {
            contenedor.setSelectedIndex(0);
        }

    }//GEN-LAST:event_botonInicioActionPerformed

    private void textContraseña2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraseña2MousePressed
        if (String.valueOf(textContraseña1.getPassword()).equals("******")) {
            textContraseña1.setText("*******");
            textContraseña1.setText("");
            textContraseña1.setForeground(Color.black);
        }
        if (textUsuario1.getText().isEmpty()) {
            textUsuario1.setText("Escriba aquí su nombre..");

            textUsuario1.setForeground(Color.black);
        }
        if (String.valueOf(textContraseña2.getPassword()).equals("*******")) {
            textContraseña2.setText("*******");
            textContraseña2.setText("");

            textContraseña2.setForeground(Color.black);
        }

    }//GEN-LAST:event_textContraseña2MousePressed

    private void textContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseña2ActionPerformed

    private void botonRegistro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistro1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistro1MouseEntered

    private void botonRegistro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistro1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistro1MouseExited

    private void botonRegistro1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistro1MousePressed
          // En este apartado creo una alerta como si estubieramos accediendo 
        javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + textUsuario.getText() + "\nContraseña: "
                + "*******", "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_botonRegistro1MousePressed

    private void botonRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistro1ActionPerformed

        String nombre = textUsuario.getText();
        String contrasena = String.valueOf(textContraseña1.getPassword());
        String contrasena2 = String.valueOf(textContraseña2.getPassword());
        usuarios = cargarUsuarios();

        crearUsuario(usuarios, nombre, contrasena, contrasena2);
        contenedor.setSelectedIndex(0);


    }//GEN-LAST:event_botonRegistro1ActionPerformed

    private void textFechaFinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFechaFinMousePressed
        //
    }//GEN-LAST:event_textFechaFinMousePressed

    private void textFechaFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaFinActionPerformed

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered

    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited

    }//GEN-LAST:event_botonGuardarMouseExited

    private void botonGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarMousePressed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTituloMousePressed

    }//GEN-LAST:event_textTituloMousePressed

    private void textTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloActionPerformed

    private void addBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBotonActionPerformed

        botonGuardar.setVisible(true);
    }//GEN-LAST:event_addBotonActionPerformed

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        botonGuardar.setVisible(true);
    }//GEN-LAST:event_modificarBotonActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBotonActionPerformed

    private void pendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendienteActionPerformed

    private void enProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enProcesoActionPerformed

    private void botonAcceder1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAcceder1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAcceder1MouseEntered

    private void botonAcceder1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAcceder1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAcceder1MouseExited

    private void botonAcceder1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAcceder1MousePressed
      
    }//GEN-LAST:event_botonAcceder1MousePressed

    private void botonAcceder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcceder1ActionPerformed

        usuarios = cargarUsuarios();
        System.out.println(usuarios);
        String nombre = textUsuario.getText();
        String contrasena = textContraseña.getText();

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe introducir un nombre de usuario");
        } else if (contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe introducir una contraseña");

        } else {

            if (usuarioCorrecto(usuarios, nombre, contrasena)) {
                contenedor.setSelectedIndex(2);

            } else if (!usuarioCorrecto(usuarios, nombre, contrasena)) {
                JOptionPane.showMessageDialog(this, "El usuario no está registrado");

            } else {
                JOptionPane.showMessageDialog(this, "La contraseña es incorrecta");
                contadorIntento++;
                if (contadorIntento == 4) {
                    JOptionPane.showMessageDialog(this, "Has fallado la contraseña demasiadas veces, vuelve a intentarlo más tarde");
                    System.exit(0);
                }
            }
        }

        }//GEN-LAST:event_botonAcceder1ActionPerformed

    private void textFechaInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFechaInicioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaInicioMousePressed

    private void textFechaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFechaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFechaInicioActionPerformed

    private void botonSalirTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirTareaActionPerformed
        int salir = JOptionPane.showConfirmDialog(this, "¿Estás seguro que deseas salir?", "", JOptionPane.YES_NO_OPTION);
        if (salir == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_botonSalirTareaActionPerformed

    private void botonVolverInicioTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverInicioTareaActionPerformed
        int volverInicio = JOptionPane.showConfirmDialog(
                this,
                "¿Está seguro de que quiere volver al menú principal?",
                "",
                JOptionPane.YES_NO_OPTION);

        if (volverInicio == JOptionPane.YES_OPTION) {
            contenedor.setSelectedIndex(0);
        }
    }//GEN-LAST:event_botonVolverInicioTareaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton addBoton;
    private javax.swing.JLabel bgFondo;
    private javax.swing.JLabel bgFondo1;
    private javax.swing.JLabel bgFondo2;
    private javax.swing.JButton botonAcceder1;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JButton botonRegistro1;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSalirTarea;
    private javax.swing.JButton botonVolverInicioTarea;
    private javax.swing.JLabel confirmarContraseña;
    private javax.swing.JTabbedPane contenedor;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel contraseña1;
    private javax.swing.JList<String> duracionLista;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JRadioButton enProceso;
    private javax.swing.JLabel estado;
    private javax.swing.JList<String> estadoLista;
    private javax.swing.JLabel fechaFin;
    private javax.swing.JLabel fechaInicio1;
    private javax.swing.JRadioButton finalizado;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JLabel iniciarSesion1;
    private javax.swing.JPanel inicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JScrollPane lista1;
    private javax.swing.JScrollPane lista2;
    private javax.swing.JScrollPane lista3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel logoName;
    private javax.swing.JLabel logoRasilu;
    private javax.swing.JLabel logoRasilu1;
    private javax.swing.JPanel menuRegistro;
    private javax.swing.JPanel menuTareas;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JLabel oclock;
    private javax.swing.JRadioButton pendiente;
    private javax.swing.JLabel registro;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JPasswordField textContraseña1;
    private javax.swing.JPasswordField textContraseña2;
    private javax.swing.JTextField textFechaFin;
    private javax.swing.JTextField textFechaInicio;
    private javax.swing.JTextField textTitulo;
    private javax.swing.JTextField textUsuario;
    private javax.swing.JTextField textUsuario1;
    private javax.swing.JLabel titulo;
    private javax.swing.JList<String> tituloLista;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    // End of variables declaration//GEN-END:variables

    public List<Usuario> cargarUsuarios() {
        // Pasamos por parametro un Usuario que añadimos List usuarios

        try ( ObjectInputStream ois = new ObjectInputStream(new FileInputStream(new File(rutaUsuario)))) {
            while (ois.available() > 0) {
                usuarios = (List<Usuario>) ois.readObject();
            }
            System.out.println("Datos cargados correctamente");
        } catch (FileNotFoundException e) {
            System.err.println("El archivo no existe: " + e.getMessage());
        } catch (IOException e) {
            System.err.println("Error de escritura del archivo: " + e.getMessage());
        } catch (ClassNotFoundException ex) {
            System.err.println("Error en el cast entre clases " + ex.getMessage());
        }
        return usuarios;
    }

    //UsuarioExiste
    public boolean isExistsUsuario(UsuarioFrame u) {
        return usuarios.contains(u);
    }

    //Crear Usuario
    public void crearUsuario(List usuarios, String nombre, String contrasena, String contrasena2) {
        Usuario buscar = new Usuario(nombre, "");

        boolean crear = true;
        boolean formatoCorrecto = true;

        if (nombre.equals(contrasena)) {
            JOptionPane.showMessageDialog(null, "El nombre de usuario no puede ser igual que la contraseña");
        } else {
            if (usuarios.contains(buscar)) {
                JOptionPane.showMessageDialog(null, "El usuario ya existe");
            } else {
                if (nombre.isEmpty() || !nombreValido(nombre)) {
                    JOptionPane.showMessageDialog(null, "Debe introducir un nombre de usuario");
                    crear = false;
                    formatoCorrecto = false;
                } else if (contrasena.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debe introducir una contraseña");
                    crear = false;
                    formatoCorrecto = false;
                } else if (contrasena2.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Debe confirmar su contraseña");
                    crear = false;
                    formatoCorrecto = false;
                } else if (!contrasena.equals(contrasena2)) {
                    JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden");
                    crear = false;
                    formatoCorrecto = false;
                } else if (nombre.length() < longMinNombreUsuario) {
                    JOptionPane.showMessageDialog(null, "El nombre de usuario debe tener al menos " + longMinNombreUsuario + " caracteres");
                    crear = false;
                    formatoCorrecto = false;
                } else if (contrasena.length() < longMinContrasenaUsuario) {
                    JOptionPane.showMessageDialog(null, "La contraseña debe tener al menos " + longMinContrasenaUsuario + " caracteres");
                    crear = false;
                    formatoCorrecto = false;
                }

                if (crear) {
                    Usuario nuevo = new Usuario(nombre, contrasena, contrasena2);
                    usuarios.add(nuevo);

                    try ( ObjectOutputStream output = new ObjectOutputStream(new FileOutputStream(new File(rutaUsuario), false))) {
                        output.writeObject(usuarios);
                        JOptionPane.showMessageDialog(null, "Usuario creado correctamente");
                        output.close();
                    } catch (IOException e) {
                        System.err.println("Error de escritura: " + e.getMessage());
                    }
                }
            }
        }
    }

    /*
    * Comprobar que el nombre es valido:
    *     Si esta vacio
    *     Son caracteres
    *     No es null
     */
    public boolean nombreValido(String nombre) {
        if (nombre.isEmpty()) {
            return false;
        }

        for (int i = 0; i < nombre.length(); i++) {
            if (nombre.charAt(i) != ' ' && !nombre.equals("null")) {
                return true;
            }
        }
        return false;
    }

    private boolean usuarioCorrecto(List<Usuario> usuarios, String nombre, String contrasena) {
        String usu = nombre + " : " + contrasena;
        String[] partes = usu.split(" : ");
        Usuario comprobar = new Usuario(partes[0], partes[1]);

        for (Object o : usuarios) {
            Usuario u = (Usuario) o;
            if (u.getNombre().toLowerCase().equals(comprobar.getNombre().toLowerCase()) && u.getContrasena().equals(comprobar.getContrasena())) {
                return true;
            }
        }
        return false;
    }

}
