/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import modelos.Usuario;

/**
 *
 * @author Silvia Tovar
 */
public class UsuarioFrame extends javax.swing.JFrame {

    private static String rutaUsuario = new String("datos/usuario.dat");
    private static String rutaTarea = new String("datos/tarea.dat");
    private static Usuario usu ;

    /**
     * Creates new form UsuarioFrame
     */
    public UsuarioFrame() {
        initComponents();
        usu = new Usuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuUsuario = new javax.swing.JTabbedPane();
        background = new javax.swing.JPanel();
        logoRasilu = new javax.swing.JLabel();
        bgFondo = new javax.swing.JLabel();
        logoName = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        textContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        registro = new javax.swing.JLabel();
        botonSalir = new javax.swing.JButton();
        botonRegistro = new javax.swing.JButton();
        botonAcceder1 = new javax.swing.JButton();
        background1 = new javax.swing.JPanel();
        logoRasilu1 = new javax.swing.JLabel();
        bgFondo1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        logo1 = new javax.swing.JLabel();
        iniciarSesion1 = new javax.swing.JLabel();
        usuario1 = new javax.swing.JLabel();
        contraseña1 = new javax.swing.JLabel();
        textUsuario1 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        textContraseña1 = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        botonInicio = new javax.swing.JButton();
        textContraseña2 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        confirmarContraseña = new javax.swing.JLabel();
        botonRegistro1 = new javax.swing.JButton();
        background2 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        bgFondo2 = new javax.swing.JLabel();
        oclock = new javax.swing.JLabel();
        logo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        duracion = new javax.swing.JLabel();
        textDuracion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        botonGuardar = new javax.swing.JButton();
        textTitulo = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        addBoton = new javax.swing.JButton();
        modificarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        lista1 = new javax.swing.JScrollPane();
        tituloLista = new javax.swing.JList<>();
        lista2 = new javax.swing.JScrollPane();
        duracionLista = new javax.swing.JList<>();
        lista3 = new javax.swing.JScrollPane();
        estadoLista = new javax.swing.JList<>();
        pendiente = new javax.swing.JRadioButton();
        enProceso = new javax.swing.JRadioButton();
        finalizado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoRasilu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo rasilu.png"))); // NOI18N
        background.add(logoRasilu, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 240, 130));

        bgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoflores.png"))); // NOI18N
        bgFondo.setText("jLabel2");
        background.add(bgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -10, 280, 600));

        logoName.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        logoName.setText("O´clock");
        background.add(logoName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 50));

        logo.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopequeño.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 280, 90));

        iniciarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        iniciarSesion.setText("INICIAR SESION");
        background.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, 50));

        usuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        usuario.setText("USUARIO");
        background.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contraseña.setText("CONTRASEÑA");
        background.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, 20));

        textUsuario.setForeground(new java.awt.Color(204, 204, 204));
        textUsuario.setText("Escriba aquí su nombre..");
        textUsuario.setAutoscrolls(false);
        textUsuario.setBorder(null);
        textUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textUsuarioMousePressed(evt);
            }
        });
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        background.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 330, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 310, 10));

        textContraseña.setForeground(new java.awt.Color(204, 204, 204));
        textContraseña.setText("jPasswordFie");
        textContraseña.setBorder(null);
        textContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraseñaMousePressed(evt);
            }
        });
        textContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseñaActionPerformed(evt);
            }
        });
        background.add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 310, 20));

        registro.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        registro.setText("¿Aún no estás registrado?");
        background.add(registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 530, -1, 30));

        botonSalir.setBackground(new java.awt.Color(221, 152, 123));
        botonSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(255, 255, 255));
        botonSalir.setText("SALIR");
        botonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonSalirMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonSalirMousePressed(evt);
            }
        });
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        background.add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 80, 30));

        botonRegistro.setBackground(new java.awt.Color(221, 152, 123));
        botonRegistro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistro.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistro.setText("REGISTRATE AQUI");
        botonRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistroMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRegistroMousePressed(evt);
            }
        });
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        background.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 140, 30));

        botonAcceder1.setBackground(new java.awt.Color(221, 152, 123));
        botonAcceder1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonAcceder1.setForeground(new java.awt.Color(255, 255, 255));
        botonAcceder1.setText("ACCEDER");
        botonAcceder1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAcceder1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAcceder1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAcceder1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonAcceder1MousePressed(evt);
            }
        });
        botonAcceder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcceder1ActionPerformed(evt);
            }
        });
        background.add(botonAcceder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 90, 30));

        menuUsuario.addTab("Usuario", background);

        background1.setBackground(new java.awt.Color(255, 255, 255));
        background1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoRasilu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo rasilu.png"))); // NOI18N
        background1.add(logoRasilu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 240, 130));

        bgFondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoflores.png"))); // NOI18N
        bgFondo1.setText("jLabel2");
        background1.add(bgFondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, -10, 280, 600));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("O´clock");
        background1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 50));

        logo1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopequeño.png"))); // NOI18N
        background1.add(logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 280, 90));

        iniciarSesion1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        iniciarSesion1.setText("NUEVA CUENTA");
        background1.add(iniciarSesion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 180, 50));

        usuario1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        usuario1.setText("NOMBRE DE USUARIO");
        background1.add(usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        contraseña1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contraseña1.setText("CONTRASEÑA");
        background1.add(contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, 20));

        textUsuario1.setForeground(new java.awt.Color(204, 204, 204));
        textUsuario1.setText("Escriba aquí su nombre..");
        textUsuario1.setAutoscrolls(false);
        textUsuario1.setBorder(null);
        textUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textUsuario1MousePressed(evt);
            }
        });
        textUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuario1ActionPerformed(evt);
            }
        });
        background1.add(textUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 330, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        background1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 310, 10));

        textContraseña1.setForeground(new java.awt.Color(204, 204, 204));
        textContraseña1.setText("jPasswordFie");
        textContraseña1.setBorder(null);
        textContraseña1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraseña1MousePressed(evt);
            }
        });
        textContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseña1ActionPerformed(evt);
            }
        });
        background1.add(textContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 170, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        background1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 310, 20));

        botonInicio.setBackground(new java.awt.Color(221, 152, 123));
        botonInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonInicio.setForeground(new java.awt.Color(255, 255, 255));
        botonInicio.setText("VOLVER A INICIO");
        botonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonInicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonInicioMousePressed(evt);
            }
        });
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });
        background1.add(botonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 140, 30));

        textContraseña2.setForeground(new java.awt.Color(204, 204, 204));
        textContraseña2.setText("jPasswordFie");
        textContraseña2.setBorder(null);
        textContraseña2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraseña2MousePressed(evt);
            }
        });
        textContraseña2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseña2ActionPerformed(evt);
            }
        });
        background1.add(textContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        background1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 310, 10));

        confirmarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        confirmarContraseña.setText("CONFIRMAR CONTRASEÑA");
        background1.add(confirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, 20));

        botonRegistro1.setBackground(new java.awt.Color(221, 152, 123));
        botonRegistro1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonRegistro1.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistro1.setText("REGISTRARSE");
        botonRegistro1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRegistro1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistro1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistro1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonRegistro1MousePressed(evt);
            }
        });
        botonRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistro1ActionPerformed(evt);
            }
        });
        background1.add(botonRegistro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 440, 110, 30));

        menuUsuario.addTab("Registro", background1);

        background2.setBackground(new java.awt.Color(255, 255, 255));
        background2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo rasilu.png"))); // NOI18N
        Logo.setToolTipText("");
        Logo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background2.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 190, 280, 130));

        bgFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondoflores.png"))); // NOI18N
        bgFondo2.setText("jLabel2");
        background2.add(bgFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 280, 580));

        oclock.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        oclock.setText("O´clock");
        background2.add(oclock, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 50));

        logo2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logopequeño.png"))); // NOI18N
        background2.add(logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 280, 90));

        titulo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        titulo.setText("TITULO");
        background2.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        duracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        duracion.setText("DURACION");
        background2.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        textDuracion.setForeground(new java.awt.Color(204, 204, 204));
        textDuracion.setText("Escriba aquí la duración de su tarea...");
        textDuracion.setAutoscrolls(false);
        textDuracion.setBorder(null);
        textDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textDuracionMousePressed(evt);
            }
        });
        textDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDuracionActionPerformed(evt);
            }
        });
        background2.add(textDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 330, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        background2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 310, 10));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        background2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 310, 20));

        botonGuardar.setBackground(new java.awt.Color(221, 152, 123));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar.png"))); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonGuardarMousePressed(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        background2.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        textTitulo.setForeground(new java.awt.Color(204, 204, 204));
        textTitulo.setText("Escriba aquí el titulo de su tarea...");
        textTitulo.setAutoscrolls(false);
        textTitulo.setBorder(null);
        textTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textTituloMousePressed(evt);
            }
        });
        textTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloActionPerformed(evt);
            }
        });
        background2.add(textTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 330, 20));

        estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estado.setText("ESTADO");
        background2.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));

        addBoton.setBackground(new java.awt.Color(242, 242, 242));
        addBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        addBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        addBoton.setText("Añadir ");
        addBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBotonActionPerformed(evt);
            }
        });
        background2.add(addBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, 40));

        modificarBoton.setBackground(new java.awt.Color(242, 242, 242));
        modificarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        modificarBoton.setText("Modificar ");
        modificarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });
        background2.add(modificarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 100, 40));

        eliminarBoton.setBackground(new java.awt.Color(242, 242, 242));
        eliminarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        eliminarBoton.setText("Eliminar");
        eliminarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });
        background2.add(eliminarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 100, -1));

        tituloLista.setBackground(new java.awt.Color(242, 242, 242));
        tituloLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        tituloLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tituloLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista1.setViewportView(tituloLista);

        background2.add(lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 110, 140));

        duracionLista.setBackground(new java.awt.Color(242, 242, 242));
        duracionLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Duración", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        duracionLista.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        duracionLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        duracionLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        duracionLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lista2.setViewportView(duracionLista);

        background2.add(lista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 110, 140));

        estadoLista.setBackground(new java.awt.Color(242, 242, 242));
        estadoLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        estadoLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        estadoLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista3.setViewportView(estadoLista);

        background2.add(lista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 140));

        pendiente.setText("PENDIENTE");
        pendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendienteActionPerformed(evt);
            }
        });
        background2.add(pendiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        enProceso.setText("EN PROCESO");
        enProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enProcesoActionPerformed(evt);
            }
        });
        background2.add(enProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        finalizado.setText("FINALIZADO");
        finalizado.setContentAreaFilled(false);
        finalizado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        background2.add(finalizado, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, -1, -1));

        menuUsuario.addTab("Tareas", background2);

        getContentPane().add(menuUsuario, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void textContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseñaActionPerformed

    private void textUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textUsuarioMousePressed
//       Cuando pasamos el cursor se cambia de color el apartado contrario y viceversa

        if (textUsuario.getText().equals("Ingrese su nombre de usuario")) {
            textUsuario.setText("");
            textUsuario.setForeground(Color.black);
        }
        if (String.valueOf(textContraseña.getPassword()).isEmpty()) {
            textContraseña.setText("********");
            textContraseña.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textUsuarioMousePressed

    private void textContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraseñaMousePressed
//Estas condiciones se ponen para que cuando escribas en un campo no se borren los datos en el otro
        if (String.valueOf(textContraseña.getPassword()).equals("********")) {
            textContraseña.setText("");
            textContraseña.setForeground(Color.black);
        }
        if (textUsuario.getText().isEmpty()) {
            textUsuario.setText("Ingrese su nombre de usuario");
            textUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textContraseñaMousePressed

    private void botonSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirMouseEntered

    private void botonSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirMouseExited

    private void botonSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonSalirMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirMousePressed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonRegistroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroMouseEntered

    private void botonRegistroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroMouseExited

    private void botonRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistroMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroMousePressed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void textUsuario1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textUsuario1MousePressed
        //       Cuando pasamos el cursor se cambia de color el apartado contrario y viceversa

        if (textUsuario.getText().equals("Ingrese su nombre de usuario")) {
            textUsuario.setText("");
            textUsuario.setForeground(Color.black);
        }
        if (String.valueOf(textContraseña.getPassword()).isEmpty()) {
            textContraseña.setText("********");
            textContraseña.setForeground(Color.gray);
        }

        if (String.valueOf(textContraseña1.getPassword()).isEmpty()) {
            textContraseña1.setText("********");
            textContraseña1.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textUsuario1MousePressed

    private void textUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuario1ActionPerformed

    private void textContraseña1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraseña1MousePressed
        //Estas condiciones se ponen para que cuando escribas en un campo no se borren los datos en el otro
        if (String.valueOf(textContraseña1.getPassword()).equals("********")) {
            textContraseña1.setText("");
            textContraseña1.setForeground(Color.black);
        }
        if (textUsuario.getText().isEmpty()) {
            textUsuario.setText("Ingrese su nombre de usuario");
            textUsuario.setForeground(Color.gray);
        }
        if (String.valueOf(textContraseña.getPassword()).equals("********")) {
            textContraseña.setText("");
            textContraseña.setForeground(Color.black);
        }
    }//GEN-LAST:event_textContraseña1MousePressed

    private void textContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseña1ActionPerformed

    private void botonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseEntered

    }//GEN-LAST:event_botonInicioMouseEntered

    private void botonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMouseExited

    }//GEN-LAST:event_botonInicioMouseExited

    private void botonInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonInicioMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInicioMousePressed

    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInicioActionPerformed

    private void textContraseña2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraseña2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseña2MousePressed

    private void textContraseña2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseña2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseña2ActionPerformed

    private void botonRegistro1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistro1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistro1MouseEntered

    private void botonRegistro1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistro1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistro1MouseExited

    private void botonRegistro1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistro1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistro1MousePressed

    private void botonRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRegistro1ActionPerformed

    private void textDuracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDuracionMousePressed
        //
    }//GEN-LAST:event_textDuracionMousePressed

    private void textDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDuracionActionPerformed

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered

    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited

    }//GEN-LAST:event_botonGuardarMouseExited

    private void botonGuardarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarMousePressed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void textTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTituloMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloMousePressed

    private void textTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloActionPerformed

    private void addBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBotonActionPerformed

        botonGuardar.setVisible(true);
    }//GEN-LAST:event_addBotonActionPerformed

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        botonGuardar.setVisible(true);
    }//GEN-LAST:event_modificarBotonActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBotonActionPerformed

    private void pendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pendienteActionPerformed

    private void enProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enProcesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enProcesoActionPerformed

    private void botonAcceder1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAcceder1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAcceder1MouseEntered

    private void botonAcceder1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAcceder1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAcceder1MouseExited

    private void botonAcceder1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAcceder1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAcceder1MousePressed

    private void botonAcceder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcceder1ActionPerformed
        
        List<Usuario> usuarios = new ArrayList();
        cargarUsuarios(usuarios);
        String nombre = textUsuario.getText();
        String contrasena = String.valueOf(textContraseña.getPassword());

        if (nombre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe introducir un nombre de usuario");
        } else if (contrasena.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe introducir una contraseña");

        }
        
        }//GEN-LAST:event_botonAcceder1ActionPerformed

    private void botonEntrarMousePressed(java.awt.event.MouseEvent evt) {
// En este apartado creo una alerta como si estubieramos accediendo 
        javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + textUsuario.getText() + "\nContraseña: "
                + "*********", "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton addBoton;
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background2;
    private javax.swing.JLabel bgFondo;
    private javax.swing.JLabel bgFondo1;
    private javax.swing.JLabel bgFondo2;
    private javax.swing.JButton botonAcceder1;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonInicio;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JButton botonRegistro1;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel confirmarContraseña;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel contraseña1;
    private javax.swing.JLabel duracion;
    private javax.swing.JList<String> duracionLista;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JRadioButton enProceso;
    private javax.swing.JLabel estado;
    private javax.swing.JList<String> estadoLista;
    private javax.swing.JRadioButton finalizado;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JLabel iniciarSesion1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JScrollPane lista1;
    private javax.swing.JScrollPane lista2;
    private javax.swing.JScrollPane lista3;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel logoName;
    private javax.swing.JLabel logoRasilu;
    private javax.swing.JLabel logoRasilu1;
    private javax.swing.JTabbedPane menuUsuario;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JLabel oclock;
    private javax.swing.JRadioButton pendiente;
    private javax.swing.JLabel registro;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JPasswordField textContraseña1;
    private javax.swing.JPasswordField textContraseña2;
    private javax.swing.JTextField textDuracion;
    private javax.swing.JTextField textTitulo;
    private javax.swing.JTextField textUsuario;
    private javax.swing.JTextField textUsuario1;
    private javax.swing.JLabel titulo;
    private javax.swing.JList<String> tituloLista;
    private javax.swing.JLabel usuario;
    private javax.swing.JLabel usuario1;
    // End of variables declaration//GEN-END:variables

    private UsuarioFrame cargarUsuarios(List usuarios) {
        UsuarioFrame e;
        try {
            // Creamos un ObjectInputStream para leer el archivo "usuario.dat"
            ObjectInputStream entrada
                    = new ObjectInputStream(new FileInputStream(rutaUsuario));
            // Leemos el objeto ControladorFile del archivo
            e = (UsuarioFrame) entrada.readObject();
            // Cerramos el flujo de entrada
            entrada.close();
        } catch (IOException | ClassNotFoundException ex) {
            // Si hay algún problema al leer el archivo, creamos un nuevo objeto ControladorFile vacío
            e = new UsuarioFrame();
        }
        // Devolvemos el objeto ControladorFile.
        return e;
    }
    
    
}
