/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author Silvia Tovar
 */
public class TareaVista extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioFrame
     */
    public TareaVista() {
        initComponents();
    
        
        
        
        botonGuardar.setVisible(false);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        bgFondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        duracion = new javax.swing.JLabel();
        textDuracion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        botonGuardar = new javax.swing.JButton();
        textTitulo = new javax.swing.JTextField();
        estado = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        addBoton = new javax.swing.JButton();
        modificarBoton = new javax.swing.JButton();
        eliminarBoton = new javax.swing.JButton();
        lista1 = new javax.swing.JScrollPane();
        tituloLista = new javax.swing.JList<>();
        lista2 = new javax.swing.JScrollPane();
        duracionLista = new javax.swing.JList<>();
        lista3 = new javax.swing.JScrollPane();
        estadoLista = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setToolTipText("");
        Logo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 250, 130));

        bgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/aaaaaaaaaaaaaa.png"))); // NOI18N
        bgFondo.setText("jLabel2");
        background.add(bgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 250, 580));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("O´clock");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 50));

        logo.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/logo rasilu11.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 280, 90));

        titulo.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        titulo.setText("TITULO");
        background.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, 20));

        duracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        duracion.setText("DURACION");
        background.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 20));

        textDuracion.setForeground(new java.awt.Color(204, 204, 204));
        textDuracion.setText("Escriba aquí la duración de su tarea...");
        textDuracion.setAutoscrolls(false);
        textDuracion.setBorder(null);
        textDuracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textDuracionMousePressed(evt);
            }
        });
        textDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textDuracionActionPerformed(evt);
            }
        });
        background.add(textDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 330, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 310, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 310, 20));

        botonGuardar.setBackground(new java.awt.Color(221, 152, 123));
        botonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/guardar.png"))); // NOI18N
        botonGuardar.setText("GUARDAR");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonGuardarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonGuardarMousePressed(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        background.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        textTitulo.setForeground(new java.awt.Color(204, 204, 204));
        textTitulo.setText("Escriba aquí el titulo de su tarea...");
        textTitulo.setAutoscrolls(false);
        textTitulo.setBorder(null);
        textTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textTituloMousePressed(evt);
            }
        });
        textTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textTituloActionPerformed(evt);
            }
        });
        background.add(textTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 330, 20));

        estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estado.setText("ESTADO");
        background.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 20));
        background.add(jSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 340, 20));

        addBoton.setBackground(new java.awt.Color(242, 242, 242));
        addBoton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        addBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/añadir.png"))); // NOI18N
        addBoton.setText("Añadir ");
        addBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBotonActionPerformed(evt);
            }
        });
        background.add(addBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 90, 40));

        modificarBoton.setBackground(new java.awt.Color(242, 242, 242));
        modificarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        modificarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/modificar.png"))); // NOI18N
        modificarBoton.setText("Modificar ");
        modificarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        modificarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarBotonActionPerformed(evt);
            }
        });
        background.add(modificarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 100, 40));

        eliminarBoton.setBackground(new java.awt.Color(242, 242, 242));
        eliminarBoton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        eliminarBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/basura.png"))); // NOI18N
        eliminarBoton.setText("Eliminar");
        eliminarBoton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        eliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBotonActionPerformed(evt);
            }
        });
        background.add(eliminarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, 100, -1));

        tituloLista.setBackground(new java.awt.Color(242, 242, 242));
        tituloLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Titulo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        tituloLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        tituloLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista1.setViewportView(tituloLista);

        background.add(lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 110, 140));

        duracionLista.setBackground(new java.awt.Color(242, 242, 242));
        duracionLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Duración", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        duracionLista.setFont(new java.awt.Font("Mongolian Baiti", 0, 12)); // NOI18N
        duracionLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        duracionLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        duracionLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lista2.setViewportView(duracionLista);

        background.add(lista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 110, 140));

        estadoLista.setBackground(new java.awt.Color(242, 242, 242));
        estadoLista.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 10))); // NOI18N
        estadoLista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        estadoLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lista3.setViewportView(estadoLista);

        background.add(lista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 110, 140));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDuracionActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered


    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseExited


    }//GEN-LAST:event_botonGuardarMouseExited

    private void textDuracionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textDuracionMousePressed
//   
    }//GEN-LAST:event_textDuracionMousePressed

    private void textTituloMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTituloMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloMousePressed

    private void textTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textTituloActionPerformed

    private void addBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBotonActionPerformed
        
        botonGuardar.setVisible(true);
    }//GEN-LAST:event_addBotonActionPerformed

    private void modificarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarBotonActionPerformed
        botonGuardar.setVisible(true);
    }//GEN-LAST:event_modificarBotonActionPerformed

    private void eliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarBotonActionPerformed

    private void botonGuardarMousePressed(java.awt.event.MouseEvent evt) {                                         
// En este apartado creo una alerta como si estubieramos guardando una tarea 
        javax.swing.JOptionPane.showMessageDialog(this, "Añadiendo nueva tarea" + textTitulo.getText() + "La duración es" + 
                textDuracion.getText(), "add", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }                                                                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TareaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TareaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TareaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TareaVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TareaVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton addBoton;
    private javax.swing.JPanel background;
    private javax.swing.JLabel bgFondo;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel duracion;
    private javax.swing.JList<String> duracionLista;
    private javax.swing.JButton eliminarBoton;
    private javax.swing.JLabel estado;
    private javax.swing.JList<String> estadoLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JScrollPane lista1;
    private javax.swing.JScrollPane lista2;
    private javax.swing.JScrollPane lista3;
    private javax.swing.JLabel logo;
    private javax.swing.JButton modificarBoton;
    private javax.swing.JTextField textDuracion;
    private javax.swing.JTextField textTitulo;
    private javax.swing.JLabel titulo;
    private javax.swing.JList<String> tituloLista;
    // End of variables declaration//GEN-END:variables
}
