/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.Color;

/**
 *
 * @author Silvia Tovar
 */
public class UsuarioVista extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioFrame
     */
    public UsuarioVista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        bgFondo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        iniciarSesion = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        contraseña = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        textContraseña = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        botonEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/img/logo rasilu.png")));
        Logo.setToolTipText("");
        Logo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Logo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 250, 130));

        bgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/aaaaaaaaaaaaaa.png"))); // NOI18N
        bgFondo.setText("jLabel2");
        background.add(bgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 250, 580));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("O´clock");
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 50));

        logo.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectorasilu/logo rasilu11.png"))); // NOI18N
        background.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 20, 280, 90));

        iniciarSesion.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        iniciarSesion.setText("INICIAR SESION");
        background.add(iniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 180, 50));

        usuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        usuario.setText("USUARIO");
        background.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        contraseña.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contraseña.setText("CONTRASEÑA");
        background.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, 20));

        textUsuario.setForeground(new java.awt.Color(204, 204, 204));
        textUsuario.setText("Escriba aquí su nombre..");
        textUsuario.setAutoscrolls(false);
        textUsuario.setBorder(null);
        textUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textUsuarioMousePressed(evt);
            }
        });
        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        background.add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 330, 20));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 310, 10));

        textContraseña.setForeground(new java.awt.Color(204, 204, 204));
        textContraseña.setText("jPasswordFie");
        textContraseña.setBorder(null);
        textContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textContraseñaMousePressed(evt);
            }
        });
        textContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textContraseñaActionPerformed(evt);
            }
        });
        background.add(textContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 170, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 310, 20));

        botonEntrar.setBackground(new java.awt.Color(221, 152, 123));
        botonEntrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        botonEntrar.setText("ENTRAR");
        botonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonEntrarMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonEntrarMousePressed(evt);
            }
        });
        botonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarActionPerformed(evt);
            }
        });
        background.add(botonEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 578, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void textContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textContraseñaActionPerformed

    private void botonEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEntrarActionPerformed

    private void botonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntrarMouseEntered


    }//GEN-LAST:event_botonEntrarMouseEntered

    private void botonEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonEntrarMouseExited


    }//GEN-LAST:event_botonEntrarMouseExited

    private void textUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textUsuarioMousePressed
//       Cuando pasamos el cursor se cambia de color el apartado contrario y viceversa

        if (textUsuario.getText().equals("Ingrese su nombre de usuario")) {
            textUsuario.setText("");
            textUsuario.setForeground(Color.black);
        }
         if (String.valueOf(textContraseña.getPassword()).isEmpty()) {
            textContraseña.setText("********");
            textContraseña.setForeground(Color.gray);
         }
    }//GEN-LAST:event_textUsuarioMousePressed

    private void textContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textContraseñaMousePressed
//Estas condiciones se ponen para que cuando escribas en un campo no se borren los datos en el otro
         if (String.valueOf(textContraseña.getPassword()).equals("********")) {
            textContraseña.setText("");
            textContraseña.setForeground(Color.black);
         }
        if (textUsuario.getText().isEmpty()) {
            textUsuario.setText("Ingrese su nombre de usuario");
            textUsuario.setForeground(Color.gray);
        }
    }//GEN-LAST:event_textContraseñaMousePressed

    private void botonEntrarMousePressed(java.awt.event.MouseEvent evt) {                                         
// En este apartado creo una alerta como si estubieramos accediendo 
        javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + textUsuario.getText() + "\nContraseña: " + 
                "*********", "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }                                                                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UsuarioVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UsuarioVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel background;
    private javax.swing.JLabel bgFondo;
    private javax.swing.JButton botonEntrar;
    private javax.swing.JLabel contraseña;
    private javax.swing.JLabel iniciarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField textContraseña;
    private javax.swing.JTextField textUsuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
